dataset_type: "Gimbal" # AirSim or Gimbal

# infer_dataset: # Gimbal
#   # - "/home/strage/gimbal_attitude_image/100hz/known_env/test_image/dji_rs3pro_20221118_145840/" # Sequence1
#   # - "/home/strage/gimbal_attitude_image/25hz/known_env/test_image/dji_rs3pro_20221118_150138/" # Sequence2
#   # - "/home/strage/gimbal_attitude_image/25hz/unknown_env/faculty_of_agriculture_region/dji_rs3pro_20221116_160432/" # seq3 unknown environment 農学部
#   - "/home/strage/gimbal_attitude_image/25hz/unknown_env/building_d/dji_rs3pro_20221118_150706/" # seq4 unknown environment D館
#   ##  - "/home/strage/gimbal_attitude_image/25hz/known_env/dji_rs3pro_20221114_162644" # Train Data, DONT USE

# infer_dataset: # AirSim
#   - "/home/strage/flight_airsim_image/sequence8"
#
infer_dataset:
    # - "/media/amsl/96fde31e-3b9b-4160-8d8a-a4b913579ca2/Master_thesis_and_IROS2023/gimbal_attitude_image/25hz/unknown_env/building_d/dji_rs3pro_20221118_150706"
    - "/home/amsl/kawai_data/Master_thesis_and_IROS2023/gimbal_attitude_image/25hz/unknown_env/building_d/dji_rs3pro_20221118_150706/"

csv_name: "data_list.csv"

# weights_top_directory: "/home/strage/integrated_attitude_estimator_log/ViT/train_log_TimeSformer_finetune_2023_01_11_8frame/train_log/"
# weights_file_name: "weights.pth"
weights_top_directory: "/home/amsl/catkin_ws/src/integrated_attitude_estimator/weights/"
# weights_file_name: "weights_2023_01_04_TimeSformer_finetune_4frame.pth"
# weights_file_name: "weights_2023_02_02_TimeSformer_pretrain_8frame_for_IROS.pth"
weights_file_name: "weights_2023_01_07_TimeSformer_pretrain_8frame.pth"

# weights_2022_12_22_resnet50_finetune_8frame.pth
# weights_2022_12_22_resnet50_finetune_4frame.pth

# infer_log_top_directory: "/home/strage/integrated_attitude_estimator_log/ViT/train_log_TimeSformer_finetune_2023_01_11_8frame/inference_test_log/"
# infer_log_top_directory: "/media/amsl/96fde31e-3b9b-4160-8d8a-a4b913579ca2/Master_thesis_and_IROS2023/integrated_attitude_estimator_log/ViT/train_log_TimeSformer_finetune_2023_01_11_8frame/inference_test_log/"
infer_log_top_directory: "/home/amsl/kawai_data/Master_thesis_and_IROS2023/integrated_attitude_estimator_log/ViT/train_log_TimeSformer_finetune_2023_01_11_8frame/inference_test_log/"
infer_log_file_name: "frame_infer_relust_seq4_25hz.csv"

yaml_name: "infer_config_seq4_25hz.yaml"

index_dict_name: "index_dict_-30_30_range_step1deg.csv"

index_csv_path: "/home/catkin_ws/src/integrated_attitude_estimator/index_dict/index_dict_-30_30_range_step1deg.csv"

hyperparameters:
  img_size: 224
  transform_params:
    do_domain_randomization: "eval" #train or eval
    resize: 224 # For ColorGitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.5
    hue: 0.25
    kernel_size: 5 # For Gaussian Blur
    sigma_min: 0.2
    sigma_max: 2.0
    equalize_p: 0.97 # For Random Equalize
    elastic_alpha: 25.0 # For ElasticTransform
  network_type: "TimeSformer" # TimeSformer or SENet
  num_classes: 63
  num_frames: 8 # 8 or 4 or 2 or 1
  deg_threshold: 30
  batch_size: 640 # 220 in TimeSformer, 640 in ResNet50
  num_epochs: 50 #50 in pretrain, 100 in finetuning
  optimizer_name: "RAdam"
  lr: 1e-5
  alpha: 5e-4
  num_workers: 40
  save_step: 10
  mean_element: 0.5
  std_element: 0.5
  do_white_makeup: False
  do_white_makeup_from_back: False
  whiteup_frame: 0
  timesformer:
    patch_size: 16
    attention_type: 'divided_space_time'
    depth: 4 #num transforemer layers
    num_heads: 12
  senet:
    resnet_model: "resnet50" # 18 34 50 101 152
